version: '3'

services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.3
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      # required
      BASE_URL: ${BASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      # optional
      TOTP_VAULT_KEY: ${TOTP_VAULT_KEY}
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}
      ENABLE_EMAIL_VERIFICATION: ${ENABLE_EMAIL_VERIFICATION}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
      # databases
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@plausible_db:5432/plausible_db
      CLICKHOUSE_DATABASE_URL: http://default:@plausible_events_db:8123/plausible_events_db
      # Google
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # geolocation
      IP_GEOLOCATION_DB: ${IP_GEOLOCATION_DB}
      GEONAMES_SOURCE_FILE: ${GEONAMES_SOURCE_FILE}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY}
      MAXMIND_EDITION: ${MAXMIND_EDITION}
      # email
      MAILER_ADAPTER: ${MAILER_ADAPTER}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_NAME: ${MAILER_NAME}
      SMTP_HOST_ADDR: ${SMTP_HOST_ADDR}
      SMTP_HOST_PORT: ${SMTP_HOST_PORT}
      SMTP_USER_NAME: ${SMTP_USER_NAME}
      SMTP_USER_PWD: ${SMTP_USER_PWD}
      SMTP_HOST_SSL_ENABLED: ${SMTP_HOST_SSL_ENABLED}
      POSTMARK_API_KEY: ${POSTMARK_API_KEY}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_BASE_URI: ${MAILGUN_BASE_URI}
      MANDRILL_API_KEY: ${MANDRILL_API_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:
